### ISSUE TITLE
Safe image sharing

### ISSUE THREAD

**Issue by DaynaLacoursiere** [DaynaLacoursiere/cmput404-project#20]
As an author, I want to feel safe about sharing images and posts with my friends - images should not be publicly accessible without authentication

**Comment by OmegaSheep** [comment]
Images are currently implemented, but given that friend lists are not in, we can't filter based on friends yet.

**Comment by DaynaLacoursiere** [comment]
Changed homepage based on Eddie's suggestion -> closes this issue
