### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by DaynaLacoursiere** [DaynaLacoursiere/cmput404-project#29]
As an author, I want to comment on posts that I can access

**Comment by DaynaLacoursiere** [comment]
Almost done - Add markdown

**Comment by OmegaSheep** [comment]
@DaynaLacoursiere : Markdown has a seperate issue that has been labelled as Milestone 2. I think we can probably close this for now and deal with the Markdown later. We need the user stories to be hammered out.
